### ISSUE TITLE
paper in the project

### ISSUE THREAD

**Issue by ChengXi-xdu** [cool-xuan/msflow#1]
I can't find the paper in the project, could you please provide it?

**Comment by cool-xuan** [comment]
We appreciate your interest in our work. The paper of this project is still underviewed, and we didn't submit a paper preprint on arxiv or what else. Please keep your attention to this github, the paper will be linked in the README.md as soon as accepted.

**Comment by cool-xuan** [comment]
Our paper is available in arXiv now, please refer to [this link](https://arxiv.org/pdf/2308.15300v1.pdf) for more details.
