### ISSUE TITLE
typo in train.model_forward()?

### ISSUE THREAD

**Issue by sunchengyi** [cool-xuan/msflow#2]
The line 35 in train.model_forward() is :
```
 z_ist, fuse_jac = fusion_flow(z_list)
```
Is this a typo? Should it be: 
```
 z_list, fuse_jac = fusion_flow(z_list)
```

**Comment by cool-xuan** [comment]
Yes, as you said, it is a typo. It should be 'z_list, fuse_jac = fusion_flow(z_list)', which refers to the output of the fusion flow. And we have already corrected this mistake in the updated version.

Thanks for the concern about our work and for pointing out this latent bug.

**Comment by sunchengyi** [comment]
Thank you for the quick response. 
Your work is very good! I am trying to reproduce your results on MVTec AD.

It seems that with the typo, the loc. AUROC is even slightly better on the bottle category.
I checked the git commit. It seems that the typo had been existing since train.py was tracked.
Did you get your results with the typo or the correct version?

**Comment by cool-xuan** [comment]
Our results are obtained by the correct version, which treats the output of fusion flow as the final results. 

The slightly better results yielded by parallel flows on the 'bottle' class are one-sided. Our msflow is proposed to address the varying defects among different products or classes, while the detection of 'bottle' does not suffer from defect region variation.
Please try more classes to validate the effectiveness of the proposed fusion flow. 

Moreover, the input size of the 'bottle' class should be set as (512, 512) to reproduce our results, which mainly affect the PRO score. The input size is specified (512 for all classes except 'transistor' with 256) in the last updated version just now.

**Comment by sunchengyi** [comment]
I run your code on MVTec AD and got the average of Det. AUROC being 99.1. Although it is not as good as the result in your paper, it is the best result up to now compared to the results from other models displayed on AnomLib (best is 98.2). MSFlow is very great!

Among all of the categories, the Det. AUROC of screw is smallest: 94.18. In your paper, it is 97.8. As you suggested, I have set input size to be (512, 512) except "transistor" with (256, 256). Is there anything, you think, that I can do to improve the performance on screw or on other categories?

**Comment by cool-xuan** [comment]
The config of 'top_k' should be 3% as demonstrated in Figure 8 of our [paper](https://arxiv.org/pdf/2308.15300v1.pdf). Even better results will be reproduced with our released code (For the Screw class, we achieve AUC.Det of 97.36% and AUC.Loc of 99.37% when we retrain the model with this codebase).

**Comment by sunchengyi** [comment]
Thank you for the update! During training, two type of scores are printed: the best scores and the last scores. Which type of the scores given in your paper is?
