### ISSUE TITLE
Could data augmentation be helpful?

### ISSUE THREAD

**Issue by sunchengyi** [cool-xuan/msflow#4]
Usually in other computer vision models, the data augmentation is used in training to improve the performance on the test data.
Is it possible to improve the performance of MSFlow by use the image augmentation?
Or is there any reason for not using the augmentation?

**Comment by cool-xuan** [comment]
For this specific task, _all training data (defect-free samples) share the same pose and appearance_. This particular property contributes a lot to unsupervised defect detection and localization, where the model only needs to one-to-one compare the pixel-level features.
However, most augmentation strategies (e.g. flip, crop, rotation) destroy this property, which is the reason for us to give up off-the-shelf augmentations.

**Comment by sunchengyi** [comment]
I see! Thank you very much!
