### ISSUE TITLE
when I try to run the training's example, I miss the error

### ISSUE THREAD

**Issue by DeepSpace98** [cool-xuan/msflow#8]
In the train.py code,

> https://github.com/cool-xuan/msflow/blob/7939eda6e99dd2a1e86989660cbc87bceddec048/train.py#L28C1-L33C25

`z, jac = paraller_flow(y, [cond, ])`  runtimeError : Expected input of shape (256,1,1), got (256, 64,64). 
I print the y and cond shape , find y.shape is (8, 256, 64, 64)  cond shape is (8, 64, 64, 64). How to solve this problem,can you help me?

**Comment by cool-xuan** [comment]
When I download our codebase from the latest version of msflow, anything works well. Maybe you can re-download our GitHub project and try it again.

**Comment by llopen** [comment]
> In the train.py code,
> 
> > [https://github.com/cool-xuan/msflow/blob/7939eda6e99dd2a1e86989660cbc87bceddec048/train.py#L28C1-L33C25](https://hub.fgit.cf/cool-xuan/msflow/blob/7939eda6e99dd2a1e86989660cbc87bceddec048/train.py#L28C1-L33C25)
> 
> `z, jac = paraller_flow(y, [cond, ])` runtimeError : Expected input of shape (256,1,1), got (256, 64,64). I print the y and cond shape , find y.shape is (8, 256, 64, 64) cond shape is (8, 64, 64, 64). How to solve this problem,can you help me?

I encounter the same issue, but it is resolved after I download freia 0.2 from https://pypi.org/ and reinstall it.
